homeassistant:
  external_url: "https://kuscarcek.si"

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.17.0.0/16
    - 127.0.0.1
    - ::1
draw_my_home:

sensor:
  - platform: template
    sensors:
        energy_daily:
          friendly_name: "Energy Daily"
          value_template: "OK"
          attribute_templates:
            usage: >
              [{% for h in range(0, now().hour + 1) %}
                {{ (0.5 + h * 0.1)|round(2) }}{% if not loop.last %}, {% endif %}
              {% endfor %}]
            neighbor_avg: >
              [{% for h in range(0, now().hour + 1) %}
                {{ (0.6 + h * 0.11)|round(2) }}{% if not loop.last %}, {% endif %}
              {% endfor %}]
        energy_weekly:
          friendly_name: "Energy Weekly"
          value_template: "OK"
          attribute_templates:
            usage: >
              [{% for d in range(0, now().weekday() + 1) %}
                {{ (18 + d * 1.3)|round(2) }}{% if not loop.last %}, {% endif %}
              {% endfor %}]
            neighbor_avg: >
              [{% for d in range(0, now().weekday() + 1) %}
                {{ (20 + d * 1.5)|round(2) }}{% if not loop.last %}, {% endif %}
              {% endfor %}]
        energy_monthly:
          friendly_name: "Energy Monthly"
          value_template: "OK"
          attribute_templates:
            usage: >
              {% set week = (now().day - 1) // 7 + 1 %}
              [{% for w in range(1, week + 1) %}
                {{ (80 + w * 4.7)|round(2) }}{% if not loop.last %}, {% endif %}
              {% endfor %}]
            neighbor_avg: >
              [{% for w in range(1, ((now().day - 1) // 7) + 2) %}
                {{ (85 + w * 5.3)|round(2) }}{% if not loop.last %}, {% endif %}
              {% endfor %}]
        energy_yearly:
          friendly_name: "Energy Yearly"
          value_template: "OK"
          attribute_templates:
            usage: >
              [{% for m in range(1, now().month + 1) %}
                {{ (400 + m * 10)|round(2) }}{% if not loop.last %}, {% endif %}
              {% endfor %}]
            neighbor_avg: >
              [{% for m in range(1, now().month + 1) %}
                {{ (410 + m * 12)|round(2) }}{% if not loop.last %}, {% endif %}
              {% endfor %}]
