services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ./homeassistant/config:/config
      - ./homeassistant/code:/config/www
    restart: unless-stopped
    network_mode: "host"  